language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-collision-failure' ]; then cd .. && eval "mv $currentfolder generator-collision-failure" && cd generator-collision-failure; fi
